#!/bin/bash

set -e

if [[ -n "${ASHLAR_BLUEPRINT_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0") {ashlar,editor}

Starts servers using docker-compose.

Arguments:
    - ashlar: Starts the Ashlar server instance.
    - editor: Starts the schema editor app.
    - <none>: Start all containers.
"
}

function checkport() {
    # Check that a given port has no processes running on it.
    if [[ $(netstat -nlp | grep ":::${1}") ]];
    then
        echo "It appears you already have a process running on port ${1}:"
        echo
        echo $(netstat -nlp | grep ":::${1}")
        echo
        echo "Terminate that process, or alter docker-compose.yml to use another port."
        exit 1
    fi
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ -z "$1" ]
    then
        # If no arguments are supplied, start all services.
        function runserver() {
            checkport 8000
            checkport 4567
            docker-compose up
        }
    else
        case "$1" in
            -h|--help)
                usage
                exit 0
                ;;

            ashlar)
                function runserver() {
                    checkport 8000
                    docker-compose run --service-ports ashlar-server manage.py runserver 0.0.0.0:8000
                }
                ;;

            editor)
                function runserver() {
                    checkport 4567
                    docker-compose run --service-ports schema-editor
                }
                ;;

            *)
                echo "ERROR: Container type '"$1"' not found."
                echo
                usage
                exit 1
                ;;
        esac
    fi
    runserver
fi
