#!/bin/bash

set -e

if [[ -n "${ASHLAR_BLUEPRINT_DEBUG}" ]]; then
    set -x
fi

# Most reliable way to get the path for this script.
# h/t: https://stackoverflow.com/questions/192292/bash-how-best-to-include-other-scripts/12694189#12694189
DIR="${BASH_SOURCE%/*}"
if [[ ! -d "$DIR" ]]
then
    DIR="$PWD"
fi

function usage() {
    echo -n "Usage: $(basename "$0") [OPTION]
Run linters and tests.
Options:
    -h --help       Display this help text
    --git           Check git commit titles
"
}

function app_tests() {
    # For now, just test that the build completes
    /bin/bash "${DIR}/update"
    echo "PASSED: Build completed successfully."
}

function git_tests() {
    # Fail build if any commit title in this branch contains these words
    if git log --oneline master.. | grep -wiE "fixup|squash|wip"
    then
        echo "FAILED: Illegal words in git commit:"
        echo
        echo $(git log --oneline master.. | grep -wiE "fixup|squash|wip")
        echo
        echo "Please squash these changes before merging."
        exit 1
    else
        echo "PASSED: Git commits are clean."
    fi
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ -z "$1" ]
    then
        # If no arguments are supplied, run app tests.
        app_tests
    else
        case "${1:-}" in
            -h|--help) usage ;;
            --git)     git_tests ;;
            *)         app_tests ;;
        esac
    fi
fi
