#!/bin/bash

set -e

if [[ -n "${ASHLAR_BLUEPRINT_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")

Builds and pulls container images using docker-compose, and runs database migrations.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Build containers.
        docker-compose build

		# Run database migrations
		docker-compose run --entrypoint="python manage.py migrate" ashlar-server
    fi
fi
